### PR TITLE
(Fix) Vesting Tab action

### LINKED ISSUE #469: Vesting Tab action
image

### PR DESCRIPTION
**Pull request by 0xDmitry**
Closes #469

### CODE REVIEW

File: src/hooks/aelin/useAelinPoolStatus.ts [hunk 1]
```diff
@@ -201,6 +202,9 @@ function useUserActions(
   derivedStatus: DerivedStatus,
 ): PoolAction[] {
   const { address: walletAddress } = useWeb3Connection()
+  const [balance] = useERC20Call(pool.chainId, pool.address, 'balanceOf', [
```
Comment (saeta-eth) [inline src/hooks/aelin/useAelinPoolStatus.ts:205]: Is there a way to avoid calling the `balanceOf `contract function here? This hook is often used and we've tried not to add requests to avoid a possible performance issue.

**Review by saeta-eth — APPROVED** [review]
