### PR TITLE
Sidebar - My Pools - Wrong numbers after disconnecting wallet

### LINKED ISSUE #403: Sidebar - My Pools - Wrong numbers after disconnecting wallet
Screen Shot 2022-06-01 at 18 38 52

### PR DESCRIPTION
**Pull request by 0xDmitry**
Closes #403

### CODE REVIEW

File: src/components/sidebar/MyPools.tsx [hunk 1]
```diff
@@ -138,23 +140,25 @@ const MyPools: React.FC = ({ ...restProps }) => {
             setActiveFilter(MyPoolsFilter.Invested)
           }}
         >
-          {`Invested (${getPools(userResponse, MyPoolsFilter.Invested).length})`}
+          {`Invested (${!isConnected ? 0 : getPools(userResponse, MyPoolsFilter.Invested).length})`}
```
Comment (saeta-eth) [inline src/components/sidebar/MyPools.tsx:143]: Is there a way to handle this within the getPools function? To avoid the ternary operator

Comment (0xDmitry) [reply src/components/sidebar/MyPools.tsx:143]: Yeah, great idea!

**Review by saeta-eth — APPROVED** [review]

**Review by 0xlinus — APPROVED** [review]
