### PR TITLE
(Bug) Fix warning

### LINKED ISSUE #494: Fix warning
image

### PR DESCRIPTION
**Pull request by 0xlinus**
Closes #494

### CODE REVIEW

File: src/hooks/aelin/useAelinPoolStatus.ts [hunk 1]
```diff
@@ -708,7 +708,7 @@ export default function useAelinPoolStatus(
   initialData?: InitialData,
 ) {
   const { pool: poolResponse, refetch: refetchPool } = useAelinPool(chainId, poolAddress, {
-    refreshInterval: ms('30s'),
+    refreshInterval: ms('5s'),
```
Comment (0xDmitry) [inline src/hooks/aelin/useAelinPoolStatus.ts:711]: It's from another PR, right?

**Review by 0xDmitry — APPROVED** [review]
